#
# _config.yml: Site-wide liquid variables for Jekyll website.  These values
# can be used in Jekyll files with the construction:
#     {{ site.tab_title }}
# For documentation, see https://jekyllrb.com/docs/variables/#site-variables
#
# Note: if you change a variable in this file, you have to restart the jekyll
# web server (typically ./.server script) in order for the variable to be updated
# on the locally served website.
#

# tab_title: Title to display in browser tab for webpage.
tab_title: "POPC2"

# data_addr: Website for Humdrum scores and derivatives.
data_addr: "https://data.nifc.humdrum.org"

# browse_index: JSON list of works for browse page.
browse_index: "https://data.nifc.humdrum.org/popc2-browse-index.json"

# lyrics_index: TEXT list of works for lyrics searching.
lyrics_index: "https://data.nifc.humdrum.org/popc2-lyrics-index.txt"

# composer_index: JSON list of composers for browse and work pages.
composer_index: "https://data.nifc.humdrum.org/popc2-composer-index.json"

# background_image: Background image for <main>
background_image: "/img/bgcbw.png"

# langauges: List of langauges available on website.
languages:
   - "EN"
   - "PL"

# debug: Print debugging statements (or not, if set to "false").
debug: "true"
# debug: "false"

# debug: Print extra debugging statements for functions that are called
# very often (and thus are not included in the regular debug level).
# debug_verbose: "true"
debug_verbose: "false"


##############################
##
## CSS Stylings -- The following variables control site-wide styles
##     (mostly colors) on the website.  These variables are used in the
##     css files found in _includes/styles, but are also stored in
##     the POPC2.STYLES object (see _includes/initialize/POPC2.js) in case
##     they are needed for dynamic content generation.
##

# h1_color: Color for H1 headings.
h1_color: "#a71b1d"

# h2_color: Color for H2 headings.
h2_color: "black"

# h3_color: Color for H3 headings.
h3_color: "#aaaaaa"

# th_color: Color for Table headings.
th_color: "#a71b1d"

# button_hover_color: Color for buttons when hovering over them.
button_hover_color: "limegreen"

# selected_langauge_color: Color to highlight the selected language in the navigator.
selected_language_color: "goldenrod"



