#
# _config.yml: Site-wide liquid variables for Jekyll website.  These values
# can be used in Jekyll files with the construction:
#     {{ site.tab_title }}
# For documentation, see https://jekyllrb.com/docs/variables/#site-variables
#
# Note: if you change a variable in this file, you have to restart the jekyll
# web server (typically ./.server script) in order for the variable to be updated
# on the locally served website.
#

# data_addr: Website for Humdrum scores and derivatives.
data_addr: "https://data.nifc.humdrum.org"

# score_index: JSON list of works for browse page.
score_index_popc2: "https://data.nifc.humdrum.org/popc2-score-index.json"
score_index_popc1: "https://data.nifc.humdrum.org/popc1-score-index.json"

# lyrics_index: TEXT list of works for lyrics searching.
lyrics_index_popc2: "https://data.nifc.humdrum.org/popc2-lyrics-index.txt"
lyrics_index_popc1: "https://data.nifc.humdrum.org/popc1-lyrics-index.txt"

# composer_index: JSON list of composers for browse and work pages.
composer_index_popc2: "https://data.nifc.humdrum.org/popc2-composer-index.json"
composer_index_popc1: "https://data.nifc.humdrum.org/popc1-composer-index.json"

# siglum_index: JSON list of RISM sigla for browse and work pages.
siglum_index: "https://data.nifc.humdrum.org/siglum-index.json"

# instrument_index: JSON list of Humdrum instrument codes for browse page.
instrument_index: "https://data.nifc.humdrum.org/instrument-index.json"

# pitch_index: TEXT list of melodic pitches for browse page searching.
pitch_index_popc2: "https://data.nifc.humdrum.org/popc2-pitch-index.txt"
pitch_index_popc1: "https://data.nifc.humdrum.org/popc1-pitch-index.txt"

# URL to the POPC-1/POPC-2 repostories on github
github_addr_popc2: "https://github.com/pl-wnifc/humdrum-polish-scores"
github_addr_popc1: "https://github.com/pl-wnifc/humdrum-chopin-first-editions"

# background_image: Background image for <main>
#background_image: "/img/bgcbw.png"
#background_image: "/img/pope-martin.jpg"
background_image: "/img/background/zielenski.png"

# composer_images: Where the composer images are stored:
composer_images: "/img/composer"

# library_images: Where the library images are stored:
library_images: "/img/siglum"

# background_color: This will be multiplied with the background image.
background_color: "#5b5765"

# langauges: List of langauges available on website.
languages:
   - "EN"
   - "PL"

# website_root: The root of the website (for relative path names).
# The variable must end in a shash.
website_root: "/"

# tab_title: Title to display in browser tab for webpage.
tab_title: "POPC2"

# debug: Print debugging statements (or not, if set to "false").
debug: "true"
# debug: "false"

# debug: Print extra debugging statements for functions that are called
# very often (and thus are not included in the regular debug level).
# debug_verbose: "true"
debug_verbose: "false"

##############################
##
## Notation settings
##

# size_increment: The increase/decrease in notation size when the larger/smaller
# button is pressed.
size_increment: "1.10"



##############################
##
## CSS Stylings -- The following variables control site-wide styles
##     (mostly colors) on the website.  These variables are used in the
##     css files found in _includes/styles, but are also stored in
##     the POPC2.STYLES object (see _includes/initialize/POPC2.js) in case
##     they are needed for dynamic content generation.
##

# primary_color: blue
primary_color: "#2d2e83"

# secondary_color: gold
secondary_color: "#b0845f"

# tertiary_color: gray
tertiary_color: "#e5e5e5"

# black_color: black
black_color: "#000000"

# h1_color: Color for H1 headings.
#h1_color: "#a71b1d"
h1_color: "#2d2e83"

# h2_color: Color for H2 headings.
h2_color: "#000000"

# h3_color: Color for H3 headings.
h3_color: "#aaaaaa"

# th_color: Color for Table headings.
#th_color: "#a71b1d"
th_color: "#2d2e83"

#browse_highlight_color: Color for active select menus on browse page.
browse_highlight_color: "#0b6166"

# button_hover_color: Color for buttons when hovering over them.
button_hover_color: "limegreen"

# navigator_hover_color: Color when hovering over top navigator buttons.
navigator_hover_color: "#dc143c"

# text_match_color: Color to highlight matches in lyrics on browse page.
text_match_color: "#dc143c"

# selected_langauge_color: Color to highlight the selected language in the navigator.
selected_language_color: "#2d2e83"

# max_content_width: Maximum width of main content
max_content_width: "1000px"


